openapi: "3.0.3"
info: 
  title: "Api Documentation"
  description: "Api Documentation"
  termsOfService: "urn:tos"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"
  
  version: "1.0"
  
servers:
  - url: "http://localhost:__PORT__"
  
tags:
  - name: "home-controller"
    description: "Handles User related opterations"
  
  - name: "pet"
    description: "Handles Pet specific information"
    
  - name: "store"
    description: "the Store Api"
    
  - name: "user"
    description: "the User Api"

paths:
  /:
    get: 
      tags: 
          - "home-controller"
      summary: "index"
      operationId: "indexUsingGET"
      responses:
        200: 
          description: "OK"
          content: 
            "*/*":
              schema: 
                type: string
  /pet:
    get:
      tags:
        - "pet"
      summary: "Get all Pets paged"
      description: "Get all Pets paged"
      operationId: "getAllPetsUsingGET"
      parameters: 
        - name: "headerValue"
          in: "header"
          description: "Header value"
          required: false
          schema:
            type: "string"
          
        - name: "page"
          in:   "query"
          required: true
          style: "form"
          schema:
            type: "integer"
            format: "int32"
        
        - name: "size"
          in:   "query"
          required: true
          style: "form"
          schema:
            type: "integer"
            format: "int32"
      
        - name: "sort"
          in: "query"
          required: false
          style: "form"
          schema:
            type: "string"
      responses:
        "200":
          description: "Successful Operation"
          content:
            "application/json":
              schema:
                type: "array"
                items: 
                  $ref: "#/components/schemas/Pet"
    put:
      tags:
        - "pet"
      summary: "Update an existing pet"
      description: "Update an existing pet by Id"
      operationId: "updatePetUsingPUT"
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Pet"
          "application/xml":
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        200:
          description: "Successful Operation"
          content:
            "application/xml":
              schema:
                $ref: "#/components/schemas/Pet"
            "application/json":
              schema:
                $ref: "#/components/schemas/Pet"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
        405:
          description: "Validation exception"
    post:
      tags:
        - "pet"
      summary: "Add a new pet to Petstore"
      description: "Add a new pet to Petstore"
      operationId: "addPetUsingPOST"
      requestBody: 
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Pet"
          "application/xml":
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        200:
          description: "Successfull Operation"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Pet"
            "application/xml":
              schema:
                $ref: "#/components/schemas/Pet"
        405:
          description: "Invalid input"


components:
  schemas:
    Category:
      title: "Category"
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: "1"
        name:
          type: "string"
          example: "Dogs"
    ModelApiResponse:
      title: "ModelApiResponse"
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        message:
          type: "string"
        type:
          type: "string"
    Order:
      title: "Order"
      type: "object"
      properties:
        complete:
          type: "boolean"
          example: false
        id:
          type: "integer"
          format: "int32"
          example: 10
        petId:
          type: "integer"
          format: "int32"
          example: 198772
        quantity:
          type: "integer"
          format: "int32"
          example: 100
        shipDate:
          type: "string"
          format: "date-time"
        status:
          type: "string"
          description: "Order Status"
          example: "approved"
          enum: [ "approved", "delivered", "placed"]
        
    Pet:
      title: "Pet"
      required:
        - "name"
        - "photoUrls"
      type: "object"
      properties:
        category: 
          $ref: "#/components/schemas/Category"
        id:
          type: "integer"
          format: "int64"
          example: 10
        name:
          type: "string"
          example: "doggie"
        photoUrls:
          type: "array"
          items:
            type: "string"
        status:
          type: "string"
          description: "pet status in store"
          enum: [ "available", "pending", "sold"]
        tags:
          type: "array"
          items: 
            $ref: "#/components/schemas/Tag"
    Tag:
      title: "Tag"
      type: "object"
      properties: 
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
            
    User:
      title: "User"
      type: "object"
      properties:
        email:
          type: "string"
          example: "john@email.com"
        firstName:
          type: "string"
          example: "John"
        id:
          type: "integer"
          format: "int32"
          example: 10
        lastName:
          type: "string"
          example: "James"
        password:
          type: "string"
          example: "123456"
        phone:
          type: "string"
          example: "12345"
        userStatus:
          type: "integer"
          description: "User Status"
          format: "int32"
          example: 1
        userName:
          type: "string"
          example: "theUser"
        